### PR TITLE
A few fixes and changes

### PR DESCRIPTION
**Pull request by cawka**
Two last commits in this pull requests add additional changes that can be ignored (switching to c++11 and moving files to boost-dbus, instead of just dbus folder (this is to prevent mixing with actual dbus headers).

Also. The example in README.md was describing non-existing things.

### CODE REVIEW

**Comment by Xenopathic** [comment]
You've changed the `#include`s in the headers to use 'relative' qualifiers (`"***.hpp"`) instead of the standard used in (most of?) Boost, which is to use fully qualified includes always. In addition, why `boost-dbus` instead of `boost/dbus` for the header path?

Also, if you are going to require C++11 (through the use of `std::function`), you might as well completely remove `functional.hpp` and `chrono.hpp`. The only issue is, I believe that Boost Chrono and Functional are slightly incompatible with the C++11 ones, so it is probably best to just use the Boost ones always (so still get rid of those surplus headers)

**Comment by bkietz** [comment]
First of all: thanks for taking the time to make a pull request. I appreciate the additions of null catch in `impl::connection` and `message::sanitize()`. These and several other changes will be merged in shortly.

I am interested in your change to `error`, but I don't know what it does and won't use it immediately.

Several of your other changes will not be used:

- I'm trying to be backwards compatible to C++98, so I'll continue to use Boost's functional and chrono.
- method inline-ing is ultimately decided by the compiler, so I'd just as soon not clutter the code with unnecessary tokens
- as @Xenopathic said, Boost uses fully qualified includes

**Comment by cawka** [comment]
@Xenopathic My intention was to incorporate boost-dbus as part of my project as a submodule without relying on installing headers to any standard location and using additional -I flags.  If talking about boost, the library uses really fully qualified includes (using <boost/...>).  To copy other boost libraries, headers may need to be moved even further, to include/boost/<dbus>

About why boost-dbus.  If headers get moved to boost/dbus, I will not be objecting using just dbus.  But right now includes could get "installed" into just dbus folder and mix with libdbus-1 library headers, which is not correct in my opinion.

About function.  As I mentioned in my pull request, I didn't mean those to be merged.  However, I believe that there should be a way to avoid either std:: or boost::function (in headers).  At least this is done with other boost::asio things.  I tried to figure out how it is done, but failed within the time I had. When I have more time, I can try to dig it further.

I cannot say anything about chrono.hpp. Boost.chrono is definitely incompatible (and much superior) to std::chrono.  I think inside boost library, std::chrono is never used directly, but I could be very wrong.

**Comment by cawka** [comment]
@bkietz About error.  I made the current hack as of necessity, as I was getting segmentation faults (when I couldn't connect to dbus bus).  To my understanding, error_category needs to be a static object, as the thrown exception stores only pointer to category and not a copy of it.  I suspect, error class needs to be redesigned a little bit, but I don't have specific suggestions as of yet.

**Comment by cawka** [comment]
@bkietz About method inlining.  While ultimately inlining is compiler decision, marking inline in headers is absolutely necessary, as if you include the same headers in two separate compilation units, you would get duplicate symbol errors. Again, I did this change only because I was getting errors :-D

**Comment by RobinMcCorkell** [comment]
@cawka I completely agree with you on the proposed move to something other than just `dbus/`, but I feel that `boost/dbus` fits better than `boost-dbus` :smile:

As for the exception situation - I noticed some very interesting behaviour with `std::exception` vs `boost::exception` (at least with my compiler and standard library): `std::exception` calculates the result of `what()` at the point of construction, so that the object going out of scope doesn't result in a segfault when `what()` is called later on. `boost::exception` doesn't seem to do this, so hacks are required :speak_no_evil: 

@bkietz Could I suggest that `functional.hpp` and `chrono.hpp` are completely removed and that the Boost versions are used everywhere? I don't see any point supporting multiple object types - the default types (the Boost ones) will get all the testing, and when someone comes along and tries to use the alternatives they will get errors. It'd be best to avoid that situation entirely IMHO

**Comment by cawka** [comment]
@Xenopathic I don't think the comment applies to std::exception.  I'm using std::runtime_error for my exceptions, which copies the supplied text string internally.  With boost::exception (at least as far as I used it) the information needs to be supplied through `error_info` mechanism (http://www.boost.org/doc/libs/1_57_0/libs/exception/doc/error_info.html).

**Pull request closed without merging**
